
name: Checkmarx One Scan 06jan
on:
  push:
    branches:
      - master
jobs:
  cx-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main
        with:
          project_name: ${{ github.repository }}
          base_uri: ${{ secrets.BASE_URI }}
          cx_tenant: ${{ secrets.TENANT }}
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.CLIENT_SECRET }}
          #additional_params: --threshold sast-high=1
          additional_params: --apikey ${{ secrets.APIKEY }}
